CREATE TABLE users (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(100) UNIQUE NOT NULL,
   user_login VARCHAR(255) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL,
   address VARCHAR(255),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   user_type VARCHAR(7) NOT NULL
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_refresh_tokens_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_tokens(user_id);

INSERT INTO users (name, email, user_login, password, address, user_type) VALUES
    ('Admin', 'admin@admin.com', 'admin', '$2a$10$pXAYJvNUBq/00VbTwKDoYecy5BJIgVTKUimFCEQzWwYB.UELYggBq', 'Rua Dez, 500 - Centro', 'ADMIN');