spring.application.name=techchallenge
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.sql.init.mode=never
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION_TIME:900000}
security.jwt.refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION_TIME:604800000}